version: 2
jobs:
  publish:
    docker:
      - image: cimg/base:2020.01
    steps:
      - add_ssh_keys:
          fingerprints:
          - 19:5c:6b:25:8c:3f:6c:46:8c:ac:dd:3c:50:15:87:92
      - checkout
      - run:
          command: ls -la
workflows:
  publish:
    jobs:
      - publish
