# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  docker-publisher:
    docker:
      - image: rozpierdalator/soldat:latest

jobs:
  publish:
    executor: docker-publisher
    steps:
      - add_ssh_keys
      - checkout
      - run: sudo apt-get install rsync
      - run: ssh -oStrictHostKeyChecking=no -t $SSH_USER@$SSH_HOST 'pkill soldat && rm -rf soldat || true'
      - run: rsync -av -e ssh * $SSH_USER@$SSH_HOST:./soldat/
      - run: ssh -oStrictHostKeyChecking=no -t $SSH_USER@$SSH_HOST 'chmod +x soldat/soldatserver'
      - run: ssh -oStrictHostKeyChecking=no -t $SSH_USER@$SSH_HOST 'tmux new -d ./soldat/soldatserver'

workflows:
  publish:
    jobs:
      - publish:
        filters:
              branches:
                only: master
