# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  docker-publisher:
    docker:
      - image: cimg/base:2020.01

jobs:
  publish:
    executor: docker-publisher
    steps:
      - add_ssh_keys
      - checkout
      - run: sudo apt-get install rsync
      - run: ssh -oStrictHostKeyChecking=no -t $SSH_USER@$SSH_HOST 'rm -rf soldat || true'
      - run: rsync -av -e ssh * $SSH_USER@$SSH_HOST:./soldat/

workflows:
  publish:
    jobs:
      - publish
